// <auto-generated />
using System;
using Aplicacao.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aplicacao.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("Aplicacao.Models.Hospede", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("JaPagou")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumeroDaReservaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NumeroDaReservaId");

                    b.ToTable("Hospedes");
                });

            modelBuilder.Entity("Aplicacao.Models.Quarto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EstaDisponivel")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Quartos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EstaDisponivel = true,
                            Numero = 105
                        },
                        new
                        {
                            Id = 2,
                            EstaDisponivel = false,
                            Numero = 205
                        },
                        new
                        {
                            Id = 3,
                            EstaDisponivel = true,
                            Numero = 305
                        });
                });

            modelBuilder.Entity("Aplicacao.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataSaida")
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroDaReserva")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quarto")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Aplicacao.Models.Hospede", b =>
                {
                    b.HasOne("Aplicacao.Models.Reserva", "NumeroDaReserva")
                        .WithMany()
                        .HasForeignKey("NumeroDaReservaId");

                    b.Navigation("NumeroDaReserva");
                });
#pragma warning restore 612, 618
        }
    }
}
